# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./wyze-exporter/wyze-exporter.sln
    - name: Build
      run: dotnet build ./wyze-exporter/wyze-exporter.sln --no-restore
    - name: Test
      run: dotnet test ./wyze-exporter/wyze-exporter.sln --no-build --verbosity normal
    - name: Build Docker Image
      working-directory: ./wyze-exporter
      run: docker build . -t imshelledin21/wyze-exporter:latest -t imshelledin21/wyze-exporter:v0.0.1
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: imshelledin21
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push imshelledin21/wyze-exporter -a

